# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fitaco < Formula
  desc ""
  homepage "https://github.com/pipejesus/homebrew-pipejesus"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pipejesus/figma-tailwind-colors/releases/download/v1.0.2/figma-tailwind-colors_Darwin_arm64.tar.gz"
      sha256 "7bcef39e1c6fdb582a01d6674b1f9c160aec8314698176d83038efbd9f086b0c"

      def install
        bin.install "figma-tailwind-colors"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pipejesus/figma-tailwind-colors/releases/download/v1.0.2/figma-tailwind-colors_Darwin_x86_64.tar.gz"
      sha256 "9470b4252fdc05d9aa8e802914ca5b16129256a39be8602632ba9dca5dcf9a00"

      def install
        bin.install "figma-tailwind-colors"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pipejesus/figma-tailwind-colors/releases/download/v1.0.2/figma-tailwind-colors_Linux_arm64.tar.gz"
      sha256 "b11ac76a41e377027958a56f9750b45dc37e86efd339f58ade8542672af51830"

      def install
        bin.install "figma-tailwind-colors"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pipejesus/figma-tailwind-colors/releases/download/v1.0.2/figma-tailwind-colors_Linux_x86_64.tar.gz"
      sha256 "2b1ed24919edf50cab046968c4ed524da0556d4f93f567c576cfa0282193f1f5"

      def install
        bin.install "figma-tailwind-colors"
      end
    end
  end
end
