# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Growkit < Formula
  desc "A tool for automating new local git repositories from starter templates"
  homepage "https://github.com/pipejesus/growkit"
  version "0.1.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pipejesus/growkit/releases/download/v0.1.0/growkit_0.1.0_darwin_amd64.tar.gz"
      sha256 "ad18dd1d0551d8596c1cb4f09a24a744ae4e8be566b1afb9d23bf193596fea1a"

      def install
        bin.install "growkit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pipejesus/growkit/releases/download/v0.1.0/growkit_0.1.0_darwin_arm64.tar.gz"
      sha256 "c46a139fa3dbd1f8e49bba6f0aded27d189a430d0f02af9e101f658769a3cc3f"

      def install
        bin.install "growkit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pipejesus/growkit/releases/download/v0.1.0/growkit_0.1.0_linux_amd64.tar.gz"
      sha256 "e31a8be35f3e6dc0017209ea25ad659dbe9af0f79cc649e344215bd411d7afbb"
      def install
        bin.install "growkit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pipejesus/growkit/releases/download/v0.1.0/growkit_0.1.0_linux_arm64.tar.gz"
      sha256 "ecf8baa75c78a3bab3cfb83fa3db2d90cbc1856f99aac06b501668f678e6d91b"
      def install
        bin.install "growkit"
      end
    end
  end

  test do
    system "#{bin}/growkit", "-h"
  end
end
