# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Towebp < Formula
  desc ""
  homepage "https://github.com/pipejesus/homebrew-pipejesus"
  version "1.0.7"
  depends_on :macos

  on_intel do
    url "https://github.com/pipejesus/towebp/releases/download/1.0.7/towebp_Darwin_x86_64.tar.gz"
    sha256 "335868d7955ca7304ef3aaaaad05ffd08fb7ed3a957c28b80e5302be6d6e68dc"

    def install
      bin.install "towebp"
    end
  end
  on_arm do
    url "https://github.com/pipejesus/towebp/releases/download/1.0.7/towebp_Darwin_arm64.tar.gz"
    sha256 "ccc15aec8899921cea634ac8ae7613adf4f4ac9936fcf180f1b591b1cb9cd6d7"

    def install
      bin.install "towebp"
    end
  end
end
