# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yayo < Formula
  desc ""
  homepage "https://github.com/pipejesus/homebrew-pipejesus"
  version "1.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pipejesus/yayo/releases/download/v1.0.5/yayo_Darwin_arm64.tar.gz"
      sha256 "7b2050292e52749fbb92817003d21d51aabfc1660d0e466ee13d3cfc773d2308"

      def install
        bin.install "yayo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pipejesus/yayo/releases/download/v1.0.5/yayo_Darwin_x86_64.tar.gz"
      sha256 "f04a665fdf6d3846714d5a8d5585c3dafd57001a1c679376459f576425302125"

      def install
        bin.install "yayo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pipejesus/yayo/releases/download/v1.0.5/yayo_Linux_arm64.tar.gz"
      sha256 "eef4ebaba08715a6f665bce28d80cabff1a14c2bfa26b9e7dee265d004a3d735"

      def install
        bin.install "yayo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pipejesus/yayo/releases/download/v1.0.5/yayo_Linux_x86_64.tar.gz"
      sha256 "8b31df5f719b77e3337dfe247841c410c92cf2cfe5392a92ba3cde9ead98ef93"

      def install
        bin.install "yayo"
      end
    end
  end
end
